### ISSUE TITLE
enable-logging for firewall is GA, but not supported by google provider (GA)

### ISSUE THREAD

**Issue by sanmmishra** [terraform-google-modules/terraform-google-network#102]
The enable-logging for firewall rules was announced GA in early 2019 but not yet supported by GCP's GA provider. It is only supported by beta provider.
In this link below, the code has been commented out, but the feature needs to be supported by google provider (GA)

https://github.com/terraform-google-modules/terraform-google-network/blob/master/modules/fabric-net-firewall/main.tf

**Comment by ludoo** [comment]
This is the wrong repository for this issue: you need to open it in the [google provider repo](https://github.com/terraform-providers/terraform-provider-google/issues), not here where we manage modules, not the actual provider resources.
