### ISSUE TITLE
Error: "enable_flow_logs": [REMOVED]

### ISSUE THREAD

**Issue by pjocke** [terraform-google-modules/terraform-google-network#111]
Error: "enable_flow_logs": [REMOVED] This field is being removed in favor of log_config. If log_config is present, flow logs are enabled. Please remove this field

The error message pretty much sums it up. Maybe pass a log_config map to the module? I tried to solve it, but didn't manage to pass an object inside of the subnet list.

**Comment by morgante** [comment]
This will be fixed in v2.0.0, see #105.
