### ISSUE TITLE
Issue adding routes with release 2.0 branch and provider 3.0

### ISSUE THREAD

**Issue by iloveicedgreentea** [terraform-google-modules/terraform-google-network#112]
```
Error: "next_hop_vpn_tunnel": only one of `next_hop_gateway,next_hop_instance,next_hop_ip,next_hop_vpn_tunnel` can be specified, but `next_hop_gateway,next_hop_instance,next_hop_ip,next_hop_vpn_tunnel` were specified.

  on .terraform/modules/vpc/main.tf line 83, in resource "google_compute_route" "route":
  83: resource "google_compute_route" "route" {
```

I get this error if I specify a route to create. This is due to the code here 

https://github.com/terraform-google-modules/terraform-google-network/blob/release/2.0/main.tf#L91

**Comment by johnroach** [comment]
I have been able to replicate this issue. this needs attention.

**Comment by johnroach** [comment]
Provided PR: https://github.com/terraform-google-modules/terraform-google-network/pull/113 which seems to resolve issue.

**Comment by johnroach** [comment]
The fix is merged in and available for release 2.0 branch.

**Comment by johnroach** [comment]
Let us please close this issue. Thank you! ( cc: @aaron-lane )

**Comment by johnroach** [comment]
Thank you @morgante !
