### ISSUE TITLE
Required providers are not configured

### ISSUE THREAD

**Issue by MarioHornero** [terraform-google-modules/terraform-google-network#118]
Hello, in the **main.tf** file seems to be a deprecated option on **subnetwork** config called "enable_flow_logs". It seems to be replaced for log_config.

When I tried to execute a terraform plan using this module, it is returning this message:

**_Error: "enable_flow_logs": [REMOVED] This field is being removed in favor of log_config. If log_config is present, flow logs are enabled. Please remove this field_**

If is possible, could you remove this field from main.tf file?

Thanks in advance.

Best regards.

**Comment by Z20BAREZ** [comment]
It's due to the terraform google provider that is now in 3.0.0-beta.1, quick fix is forcing your provider to : version = "<3.0", I will do a long term fix

**Comment by aaron-lane** [comment]
The fix should be to configure [required providers](https://www.terraform.io/docs/configuration/terraform.html#specifying-required-provider-versions) for the root module and submodules.

The required range should be `~> 0.12.6`.
