### ISSUE TITLE
Bug in firewall module

### ISSUE THREAD

**Issue by shashank-google** [terraform-google-modules/terraform-google-network#121]
Example: https://github.com/terraform-google-modules/terraform-google-network/tree/master/examples/submodule_firewall

Creates internal firewall rule (module.test-firewall-submodule.google_compute_firewall.allow-internal[0]) only with icmp. Will tcp, udp ingress rules are skipped. Can you please check ?

**Comment by aaron-lane** [comment]
@SKozlovsky please investigate this and provide a fix if it is reproducible.
