### ISSUE TITLE
FR: Ability to set Sample Rate of subnet flow logs

### ISSUE THREAD

**Issue by shashank-google** [terraform-google-modules/terraform-google-network#125]
Feature Request to set sample rate of subnet flow logs. 
Gcp's default is 50% but we want it to be 100%.

**Comment by morgante** [comment]
We will have support for this in the 2.0 release: https://github.com/terraform-google-modules/terraform-google-network/pull/86/files#diff-04c6e90faac2675aa89e2176d2eec7d8R49
