### ISSUE TITLE
Bump terraform-provider-google to 3.1.0

### ISSUE THREAD

**Issue by parabolic** [terraform-google-modules/terraform-google-network#128]
Hi People, 
I was wondering if there's a possibility to bump the `terraform-provider-google` version to the latest `3.1.0`, since there are quite some bugs that are fixed with it. The version is pinned to `2.19.0` and this is preventing me from using the network module in the same state. The only options for now I have are to use another state,  fork, drop or bump it via a PR.
If you agree with bumping the version I can also open a PR against the module with it.
Thanks!

**Comment by morgante** [comment]
We can bump the version if it's working, but will need to confirm nothing breaks. Happy to look at a PR which changes the required version and version used in examples.

**Comment by parabolic** [comment]
Thanks for the reply @morgante . I can test the module on our test account by locally bumping the provider version and will post back the results in the PR.

**Comment by bharathkkb** [comment]
@morgante I tested it out the other day for while trying to upgrade the GKE module along with examples that use network module but seems to be failing due to this bug in provider for 3.1.0
https://github.com/terraform-providers/terraform-provider-google/issues/5024

**Comment by bharathkkb** [comment]
3.3.0 has been released which should address terraform-providers/terraform-provider-google#5024 by providing workaround 
https://github.com/GoogleCloudPlatform/magic-modules/pull/2837
I will start testing the module today
