### ISSUE TITLE
Create complex routing examples for next_hop_ilb and proxy-only networks

### ISSUE THREAD

**Issue by nick4fake** [terraform-google-modules/terraform-google-network#132]
I've covered beta provider features for subnet and route in this PR:
https://github.com/terraform-google-modules/terraform-google-network/pull/124

It introduces two new submodules - routes-beta and subnetworks-beta, example and tests that simply check for values being passed to target resources and utilized by GCP.

What we miss here are two complex examples showing how relevant fields actually work, and tests covering it:
- for subnet.purpose and subnet.role (proxy-only networks) we need to set up internal HTTP(S) and check if IPs are assigned from the proxy-only network. We might also want to check active/backup subnets. More info: https://cloud.google.com/load-balancing/docs/l7-internal/proxy-only-subnets
- for route.next_hop_ilb we need an example with internal forwarding rule actualy targeting something

**Comment by nick4fake** [comment]
@aaron-lane

**Comment by aaron-lane** [comment]
Yes, that all sounds reasonable.
