### ISSUE TITLE
Run tests in parallel on CI

### ISSUE THREAD

**Issue by nick4fake** [terraform-google-modules/terraform-google-network#133]
We should consider splitting tests as currently they run one-by-one and take some time.

Example in GKE repo:
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/build/int.cloudbuild.yaml

**Comment by bharathkkb** [comment]
@nick4fake I have taken care of this in #134 since I was having a hard time figuring out which step my CI failed.
