### ISSUE TITLE
Example on main page doesn't work

### ISSUE THREAD

**Issue by scarolan** [terraform-google-modules/terraform-google-network#138]
The example code on the main page should work for new users with no modification. It throws these errors if you try to use it as-is:

```
Error: "log_config.0.metadata": one of `log_config.0.aggregation_interval,log_config.0.flow_sampling,log_config.0.metadata` must be specified

  on .terraform/modules/vpc/terraform-google-modules-terraform-google-network-3e28d88/modules/subnets/main.tf line 28, in resource "google_compute_subnetwork" "subnetwork":
  28: resource "google_compute_subnetwork" "subnetwork" {

Error: "log_config.0.aggregation_interval": one of `log_config.0.aggregation_interval,log_config.0.flow_sampling,log_config.0.metadata` must be specified

  on .terraform/modules/vpc/terraform-google-modules-terraform-google-network-3e28d88/modules/subnets/main.tf line 28, in resource "google_compute_subnetwork" "subnetwork":
  28: resource "google_compute_subnetwork" "subnetwork" {

Error: "log_config.0.flow_sampling": one of `log_config.0.aggregation_interval,log_config.0.flow_sampling,log_config.0.metadata` must be specified

  on .terraform/modules/vpc/terraform-google-modules-terraform-google-network-3e28d88/modules/subnets/main.tf line 28, in resource "google_compute_subnetwork" "subnetwork":
  28: resource "google_compute_subnetwork" "subnetwork" {
```

**Comment by morgante** [comment]
Please share your full config and logs. I'm not sure what isn't working, because the main example config is reflected in this [example](https://github.com/terraform-google-modules/terraform-google-network/tree/master/examples/simple_project) which we test automatically.

In particular, please also share `terraform version` and `terraform plan`

**Comment by billyfoss** [comment]
I ran into this after upgrading my google-beta provider.  It is explained with https://www.terraform.io/docs/providers/google/guides/version_3_upgrade.html#at-least-one-of-aggregation_interval-flow_sampling-or-metadata-is-now-required-on-google_compute_subnetwork-log_config

**Comment by morgante** [comment]
@billyfoss What did you have to do for it to work?
