### ISSUE TITLE
Module v2.0.x errors with "Invalid for_each argument"

### ISSUE THREAD

**Issue by skinlayers** [terraform-google-modules/terraform-google-network#151]
Using terraform 0.12.18 & 0.12.20 with google & google-beta providers 0.20.1.
Reverting to module ~> 1.4 resolves the error.

snippet:
```
# Based on https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/examples/safer_cluster/network.tf
resource "random_string" "net_suffix" {
  length  = 4
  special = false
  upper   = false
}

locals {
  resource_prefix     = "foo"
  network_name       = "${local.resource_prefix}-network-${random_string.net_suffix.result}"
  subnet_name        = "${local.resource_prefix}-subnet-${random_string.net_suffix.result}"
  subnet_ip          = "10.0.0.0/17"
  pods_range_name    = "${local.resource_prefix}-ip-range-pods-${random_string.net_suffix.result}"
  pods_ip_cidr_range = "192.168.0.0/18"
  svc_range_name     = "${local.resource_prefix}-ip-range-svc-${random_string.net_suffix.result}"
  svc_ip_cidr_range  = "192.168.64.0/18"
}

module "gcp-network" {
  source       = "terraform-google-modules/network/google"
  version      = "~> 2.0"
  project_id   = data.google_client_config.default.project
  network_name = local.network_name

  subnets = [
    {
      subnet_name   = local.subnet_name
      subnet_ip     = local.subnet_ip
      subnet_region = data.google_client_config.default.region
    },
    # {
    #   subnet_name   = local.master_auth_subnetwork
    #   subnet_ip     = "10.60.0.0/17"
    #   subnet_region = var.region
    # },
  ]

  secondary_ranges = {
    "${local.subnet_name}" = [
      {
        range_name    = local.pods_range_name
        ip_cidr_range = local.pods_ip_cidr_range
      },
      {
        range_name    = local.svc_range_name
        ip_cidr_range = local.svc_ip_cidr_range
      },
    ]
  }
}
```

Error:
```
Error: Invalid for_each argument

  on .terraform/modules/gcp-network/terraform-google-modules-terraform-google-network-b6c8299/modules/subnets/main.tf line 29, in resource "google_compute_subnetwork" "subnetwork":
  29:   for_each                 = local.subnets

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```

**Comment by morgante** [comment]
In 2.0, we [changed](https://github.com/terraform-google-modules/terraform-google-network/pull/73) to keying off subnet names and using `for_each`. This means subnet names must be known at plan-time.

Because you are injecting a random ID into your subnet names, it's impossible to know their name ahead of time. I would recommend either:
1. Removing the random ID from the subnet names. Subnets are already localized per project + region.
2. Doing a targeted apply first (`terraform apply -target=random_string.net_suffix`) before trying to create the subnets.

**Comment by skinlayers** [comment]
Ah! Thank you!

**Comment by sonnysideup** [comment]
https://github.com/terraform-google-modules/terraform-google-network/issues/151#issuecomment-580574591

I don't believe this is a good solution if your building a module composed of the `"terraform-google-modules/network/google"` module and others using automation software. Subnets may be localized per project and region, but you cannot create multiple, as an example, gke cluster in multiple vpcs using the same subnet name.

Targeting the apply creates an extra steps, hence, there should be a better solution here.

**Comment by voxmaster** [comment]
This should be documented on the first page so that people won't spend days figuring out what is wrong with the config.
