### ISSUE TITLE
create_network flag is not respected in 2.1.1, only 1.5.0

### ISSUE THREAD

**Issue by spacertechie** [terraform-google-modules/terraform-google-network#156]
`[x:~/terraform-modules/terraform-google-network] master 7s ± grep -r "create_network" *
CHANGELOG.md:  data source attributes when `create_network` = `true`. [#94]
variables.tf:variable "create_network" {
[x:~/terraform-modules/terraform-google-network] master ±`

When running plan in 2.1.1 it said it would re-create the network.

**Comment by morgante** [comment]
Correct, in the v2 module we have removed the ability to invoke the root module without creating networks. This means the `create_network` variable is no longer functional and should be removed (bug).

If you want to create subnets without creating the network itself, you should invoke the submodule like the [root module](https://github.com/terraform-google-modules/terraform-google-network/blob/master/main.tf#L30) does.

**Comment by spacertechie** [comment]
'preciate the info, thanks!
