### ISSUE TITLE
Use gcloud terraform module for restricted environments

### ISSUE THREAD

**Issue by mhamrah** [terraform-google-modules/terraform-google-network#161]
Hi team, this is a great module but unable to be run in Terraform Cloud due to the inability to install dependencies. The terraform google modules oganization has the https://github.com/terraform-google-modules/terraform-google-gcloud module, which some other projects like project-factory use for executing gcloud commands. It would be great if this module would use that wrapper for gcloud so this module is more portable across various environments.

Thank you.

**Comment by morgante** [comment]
Which part raised an error for you in Terraform Cloud?

**Comment by mhamrah** [comment]
The gcloud binary can't be found.
