### ISSUE TITLE
enable_logging extra_attribute not working for firewall rules

### ISSUE THREAD

**Issue by wfleisher** [terraform-google-modules/terraform-google-network#162]
Able to get disabled, and priority to work in extra_attribute but not enable_logging.

Terraform v0.12.9
+ provider.google v3.11.0

**Comment by wfleisher** [comment]
Whoops had a brain fart moment. Forgot I was running from terraform registry, Downloaded master branch and changed source. Working now.

**Comment by TigerC10** [comment]
Hoping this gets solved in #223 release 3.0.0, as this is extremely annoying to deal with.
