### ISSUE TITLE
Firewall dynamic block not working

### ISSUE THREAD

**Issue by mholleville** [terraform-google-modules/terraform-google-network#166]
Hello,

I'm trying to use `firewall` module with example. But when I try `terraform plan` I have the following error :

```bash
Error: "allow": only one of `allow,deny` can be specified, but `allow,deny` were specified.
```

I think we have conflict with the `dynamic` blocks :

```bash
  dynamic "allow" {
    for_each = [for rule in each.value.rules : rule if each.value.action == "allow"]
    iterator = rule
    content {
      protocol = rule.value.protocol
      ports    = rule.value.ports
    }
  }

  dynamic "deny" {
    for_each = [for rule in each.value.rules : rule if each.value.action == "deny"]
    iterator = rule
    content {
      protocol = rule.value.protocol
      ports    = rule.value.ports
    }
  }
```

**Comment by mholleville** [comment]
Issue --> https://github.com/hashicorp/terraform-plugin-sdk/issues/280

**Comment by morgante** [comment]
If you upgrade to using the 3.3.0 Terraform provider, this should be fixed - https://github.com/terraform-providers/terraform-provider-google/blob/master/CHANGELOG.md#330-december-17-2019

See https://github.com/terraform-providers/terraform-provider-google/issues/5024.
