### ISSUE TITLE
Error in fabric-net-firewall output

### ISSUE THREAD

**Issue by forest** [terraform-google-modules/terraform-google-network#184]
When passing in the `subnet_ips` from the network module to the `internal_ranges` value in firewall like the example I'm getting the following error.

https://github.com/terraform-google-modules/terraform-google-network/blob/master/examples/submodule_firewall/main.tf#L127

```
Error: Invalid function argument

  on outputs.tf line 6, in output "internal_ranges":
   6:     ranges  = var.internal_ranges_enabled ? join(",", var.internal_ranges) : ""
    |----------------
    | var.internal_ranges is "[\"10.128.0.0/20\"]"

Invalid value for "lists" parameter: list of string required.
```

Commenting out this line fixes the error.

https://github.com/terraform-google-modules/terraform-google-network/blob/master/modules/fabric-net-firewall/outputs.tf#L22

**Comment by forest** [comment]
This is actually an issue with terragrunt and terraform. For the terragrunt inputs to be encoded correctly and passed to terraform the variables all need types defined.

**Comment by bharathkkb** [comment]
@forest we will be happy to review a PR to add types to that module.

**Comment by forest** [comment]
Sounds good. Will submit one.
