### ISSUE TITLE
Optional Creation of Resources

### ISSUE THREAD

**Issue by enderv** [terraform-google-modules/terraform-google-network#188]
Would like the ability to be able to optionally create the module resources. An input variable like `create_vpc` for example.

Use Case: Writing a module and want to be able to allow people to provide a vpc or create one on their behalf if not supplied. Currently there does not appear to be a way to do so using this module as I would have to always create another vpc. If I'm reading things correctly it used to exist but was removed at one point.

**Comment by morgante** [comment]
Hi there! In the interest of simplicity we removed this functionality from the top level module.

Instead, we decomposed the functionality into submodules. So if you want to add subnets to an existing network you can directly invoke the subnets module: https://github.com/terraform-google-modules/terraform-google-network/tree/master/modules

**Comment by enderv** [comment]
So if i'm understanding right use the submodules with empty lists if i don't want it to create anything (mainly looking at subnets on this one).
But I still don't see an optional create on vpc submodule so I would still run into the same issue it looks like?

**Comment by morgante** [comment]
There's a separate VPC module which you can include only if you want to create a VPC - https://github.com/terraform-google-modules/terraform-google-network/tree/master/modules/vpc

**Comment by enderv** [comment]
Sorry if I am misunderstanding but including the module is an all or nothing operation. Which brings me back to the original issue where I need the ability to optionally create the vpc and it's various parts depending on terraform variable values.

**Comment by morgante** [comment]
I see. Our decision was that such a use case is sufficiently rare (and added complexity) that we'd rather not supported it in the module itself.

You might be interested in knowing that the upcoming Terraform 0.13 beta will support conditional modules: https://github.com/hashicorp/terraform/issues/25016
