### ISSUE TITLE
Support/Allow Terraform 0.13

### ISSUE THREAD

**Issue by jai** [terraform-google-modules/terraform-google-network#196]
Hi all - currently this module is semver-locked to Terraform 0.12.6, are we able to relax this to allow 0.13 or are there any known breaking changes? Happy to contribute/help out as needed.

**Comment by morgante** [comment]
If you're able to test with Terraform 0.13 we're happy to accept a PR. Similar PR example: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/621

**Comment by bharathkkb** [comment]
I have this staged from when I did the other modules. Will send a PR soon.
