### ISSUE TITLE
Dedicated firewall rules module + adding to top level module

### ISSUE THREAD

**Issue by umairidris** [terraform-google-modules/terraform-google-network#199]
Currently the only CFT module to create firewall rules seems to be https://github.com/terraform-google-modules/terraform-google-network/tree/master/modules/fabric-net-firewall.

This seems to create a few default firewall rules and also needs to be a separate module call.

There is functionality to create custom rules. Would you be willing to accept a PR that pulls the custom rules logic out to its own submodule and adds it under the top level network module? Thus it would allow a user to create a network with custom firewall rules from one call.

**Comment by morgante** [comment]
Yeah I think we need to refactor the firewall rules module a bit. Here's what I'd like to see:

1. Split the core rules logic into its own submodule
2. Put the default rules in a submodule (which calls the core rules module)

**Comment by morgante** [comment]
Still needs to happen.
