### ISSUE TITLE
Warning: Quoted references are deprecated in peering module

### ISSUE THREAD

**Issue by imrannayer** [terraform-google-modules/terraform-google-network#203]
Getting warning message when executing network peering module.

Warning: Quoted references are deprecated

https://github.com/terraform-google-modules/terraform-google-network/blob/master/modules/network-peering/main.tf

  30:   depends_on = ["null_resource.module_depends_on"]

In this context, references are expected literally rather than in quotes.
Terraform 0.11 and earlier required quotes, but quoted references are now
deprecated and will be removed in a future version of Terraform. Remove the
quotes surrounding this reference to silence this warning.

(and 4 more similar warnings elsewhere)

**Comment by bharathkkb** [comment]
Fixed by https://github.com/terraform-google-modules/terraform-google-network/pull/216
