### ISSUE TITLE
Secondary Ranges

### ISSUE THREAD

**Issue by robertrockjr** [terraform-google-modules/terraform-google-network#206]
The secondary_ranges section doesn't appear to be working. 

secondary_ranges = {
        subnet-01 = [
            {
                range_name    = "subnet-01-secondary-01"
                ip_cidr_range = "192.168.64.0/24"
            },
        ]

        subnet-02 = []
    }

Visual Studio code doesn't show the range_name or ip_cidr_range strings correctly. All other strings are colored dark orange except these ones. When I run tf apply the secondary ranges do not show up on the VPC's subnet. 
![Screen Shot 2020-09-24 at 12 16 13 PM](https://user-images.githubusercontent.com/68246928/94172213-36ec6900-fe60-11ea-9af7-40fbc613fea5.png)

**Comment by morgante** [comment]
This sounds like an issue which should be filed on the Visual Studio repo.

**Comment by robertrockjr** [comment]
> This sounds like an issue which should be filed on the Visual Studio repo.
> 
> If you have an issue with _deploying_ the code ("not working"), feel free to ask here.

Well, I only pointed out the Visual Studio code issue because the secondary_subnet do not get added to the VPC's. I don' think this is a Visual Studio code issue. Are you able to make the secondary_ranges work?

**Comment by morgante** [comment]
Yes, secondary ranges work in experience (and our automated tests).

What happens when you apply your Terraform plan? Does it raise errors or not have the secondary ranges show up?

**Comment by robertrockjr** [comment]
No error. The secondary ranges just don't show up on the subnet. Here is my
code:

module "vpc" {
source = "git@github.ascension.org:
Ascension/terraform-modules-vpc-network.git"
project_id = module.project.project_id
network_name = "${var.company}-${var.ministry}-${var.app}-${var.env}-vpc-1"
routing_mode = "GLOBAL"

subnets = [
{
subnet_name = "${var.company}-${var.ministry}-${var.app}-${var.env}-241-32"
subnet_ip = "10.246.241.32/27"
subnet_region = var.region
subnet_private_access = "true"
subnet_flow_logs = "true"
description = "Subnet for General Traffic. On-prem data to GCP"
}
]
secondary_ranges = {
subnet-01 = [
{
range_name = "subnet-01-secondary-01"
ip_cidr_range = "172.18.42.0/28"
},
]
}
}


On Thu, Sep 24, 2020 at 12:32 PM Morgante Pell <notifications@github.com>
wrote:

> Yes, secondary ranges work in experience (and our automated tests).
>
> What happens when you apply your Terraform plan? Does it raise errors or
> not have the secondary ranges show up?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://clicktime.symantec.com/a/1/pWtyUfri_OlY9I5S0U6oQDNKzkd-lBzqUTssiQ5PjL4=?d=yyyxe_6AHxIVdRMg2hJJc97p4UYUQTTpS1lRyx_Dweedk3RIZaaDazQZMTUMF_T8PHPccAa2TKQIviyPGD1CqvO9AYEUBzY53f4aL02rdk44SsFPDbbLVPtZLW_fjcGUY_jcDdQ0yT6XfH8dlzKIWvzYyG5Nh2y36b2p97hKZT4gLZp07os4cb0BiNoEwKzTaWgoQklTrl7c7f3zzAM1e1QyuWPl3r-dhKV2QgtURbnpPi95qiH9qpzZXIj5qAUKXJWsoatKAD_X4LQ8149u-J85rUqatTn1isJII40oQ06uG-wqrQ3wjcvg3DMtXOXs-L1pyWtg9dbzZIMK2ak4hTFT8S1aZNAFr7WlDgfia5FsYu5qUeTIGUCdN0vXeGrIpPEH7JcRTWJgXYFxRAMRE-bu-I0pBQ-plu5PGdy3M9OdCyPA7Xb-dBwBZp1LDsRJ9YshPX_2pC_RDYRB8oaTEqp8uc5WQND_6tWiJ06Nj_o5QzmUj956curcLzRzv46PM_L9Loe6ppkoxs55Nfw%3D&u=https%3A%2F%2Fgithub.com%2Fterraform-google-modules%2Fterraform-google-network%2Fissues%2F206%23issuecomment-698453813>,
> or unsubscribe
> <https://clicktime.symantec.com/a/1/v09H5NDOW74yj31kWETbwdA60Ni6muWX0VwvJ5keM7A=?d=yyyxe_6AHxIVdRMg2hJJc97p4UYUQTTpS1lRyx_Dweedk3RIZaaDazQZMTUMF_T8PHPccAa2TKQIviyPGD1CqvO9AYEUBzY53f4aL02rdk44SsFPDbbLVPtZLW_fjcGUY_jcDdQ0yT6XfH8dlzKIWvzYyG5Nh2y36b2p97hKZT4gLZp07os4cb0BiNoEwKzTaWgoQklTrl7c7f3zzAM1e1QyuWPl3r-dhKV2QgtURbnpPi95qiH9qpzZXIj5qAUKXJWsoatKAD_X4LQ8149u-J85rUqatTn1isJII40oQ06uG-wqrQ3wjcvg3DMtXOXs-L1pyWtg9dbzZIMK2ak4hTFT8S1aZNAFr7WlDgfia5FsYu5qUeTIGUCdN0vXeGrIpPEH7JcRTWJgXYFxRAMRE-bu-I0pBQ-plu5PGdy3M9OdCyPA7Xb-dBwBZp1LDsRJ9YshPX_2pC_RDYRB8oaTEqp8uc5WQND_6tWiJ06Nj_o5QzmUj956curcLzRzv46PM_L9Loe6ppkoxs55Nfw%3D&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQIV3ED5JTIRT5D6RVA7CTTSHNYBZANCNFSM4RYQDRQQ>
> .
>


-- 
Warm Regards,

Robert (Bob) Rock
Cloud Strategy & Services - Cloud Engineer
Ascension Technologies
(989) 513-0772


CONFIDENTIALITY NOTICE: This email message and any accompanying data or files is confidential and may contain privileged information intended only for the named recipient(s). If you are not the intended recipient(s), you are hereby notified that the dissemination, distribution, and or copying of this message is strictly prohibited. If you receive this message in error, or are not the named recipient(s), please notify the sender at the email address above, delete this email from your computer, and destroy any copies in any form immediately. Receipt by anyone other than the named recipient(s) is not a waiver of any attorney-client, work product, or other applicable privilege.

**Comment by morgante** [comment]
@robertrockjr Please share your Terraform plan.

**Comment by bharathkkb** [comment]
@robertrockjr the secondary range key is wrong, it should be the name of the subnet.
```diff
module "vpc" {
  source       = "git@github.ascension.org:Ascension/terraform-modules-vpc-network.git"
  project_id   = module.project.project_id
  network_name = "${var.company}-${var.ministry}-${var.app}-${var.env}-vpc-1"
  routing_mode = "GLOBAL"

  subnets = [
    {
      subnet_name           = "${var.company}-${var.ministry}-${var.app}-${var.env}-241-32"
      subnet_ip             = "10.246.241.32/27"
      subnet_region         = var.region
      subnet_private_access = "true"
      subnet_flow_logs      = "true"
      description           = "Subnet for General Traffic. On-prem data to GCP"
    }
  ]
  secondary_ranges = {
+    "${var.company}-${var.ministry}-${var.app}-${var.env}-241-32" = [
      {
        range_name    = "subnet-01-secondary-01"
        ip_cidr_range = "172.18.42.0/28"
      },
    ]
  }
}
```

**Comment by robertrockjr** [comment]
Thanks, Bharath. I'll give that a shot! :)

On Thu, Sep 24, 2020 at 6:28 PM Bharath KKB <notifications@github.com>
wrote:

> @robertrockjr
> <https://clicktime.symantec.com/33tNGhYbVuhL23LkhFSRYWu7Vc?u=https%3A%2F%2Fgithub.com%2Frobertrockjr>
> the secondary range key is wrong, it should be the name of the subnet.
>
> module "vpc" {
>   source       = "git@github.ascension.org:Ascension/terraform-modules-vpc-network.git"
>   project_id   = module.project.project_id
>   network_name = "${var.company}-${var.ministry}-${var.app}-${var.env}-vpc-1"
>   routing_mode = "GLOBAL"
>
>   subnets = [
>     {
>       subnet_name           = "${var.company}-${var.ministry}-${var.app}-${var.env}-241-32"
>       subnet_ip             = "10.246.241.32/27"
>       subnet_region         = var.region
>       subnet_private_access = "true"
>       subnet_flow_logs      = "true"
>       description           = "Subnet for General Traffic. On-prem data to GCP"
>     }
>   ]
>   secondary_ranges = {+    "${var.company}-${var.ministry}-${var.app}-${var.env}-241-32" = [
>       {
>         range_name    = "subnet-01-secondary-01"
>         ip_cidr_range = "172.18.42.0/28"
>       },
>     ]
>   }
> }
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://clicktime.symantec.com/33Ujcgc7swjdwtERgnvy2tU7Vc?u=https%3A%2F%2Fgithub.com%2Fterraform-google-modules%2Fterraform-google-network%2Fissues%2F206%23issuecomment-698620944>,
> or unsubscribe
> <https://clicktime.symantec.com/3EPJYchef3Rvytoz1UE2mJo7Vc?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQIV3EH3HNGFM7U4NOHRNQ3SHPB2DANCNFSM4RYQDRQQ>
> .
>


-- 
Warm Regards,

Robert (Bob) Rock
Cloud Strategy & Services - Cloud Engineer
Ascension Technologies
(989) 513-0772


CONFIDENTIALITY NOTICE: This email message and any accompanying data or files is confidential and may contain privileged information intended only for the named recipient(s). If you are not the intended recipient(s), you are hereby notified that the dissemination, distribution, and or copying of this message is strictly prohibited. If you receive this message in error, or are not the named recipient(s), please notify the sender at the email address above, delete this email from your computer, and destroy any copies in any form immediately. Receipt by anyone other than the named recipient(s) is not a waiver of any attorney-client, work product, or other applicable privilege.
