### ISSUE TITLE
Support custom MTU when creating VPCs

### ISSUE THREAD

**Issue by memes** [terraform-google-modules/terraform-google-network#220]
When deploying it would be great if the module supported setting MTU on VPCs now that it has gone GA. Setting default to 1460 will preserve existing behaviour.

*NOTE:* This would change the Google provider dependency to [3.45.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v3.45.0).

**Comment by bharathkkb** [comment]
fixed by #221
