### ISSUE TITLE
Provide ability to delete default VPC gateway route on network creation

### ISSUE THREAD

**Issue by bmenasha** [terraform-google-modules/terraform-google-network#25]
See https://github.com/terraform-google-modules/terraform-google-project-factory/issues/135

Can we add an option to delete default VPC gateway route on the created VPC?

A customer is asking for this feature as they wish to intercept all egress traffic with a security device. They will create their own route for this interception and routing of traffic from the security device to the gateway.

Thanks!

**Comment by glarizza** [comment]
PR #29 addresses this issue and was merged today

**Comment by bmenasha** [comment]
Wow. Thank you very much Gary!

**Comment by bmenasha** [comment]
Thank you very much Gary! this is great.

**Comment by drebes** [comment]
GoogleCloudPlatform/magic-modules#1539 is open to do this directly on the provider. Once merged you can remove the local-exec.

**Comment by andreyk-code** [comment]
nice, thank you @drebes!
