### ISSUE TITLE
addressing submodule 'subnets' for terraform import

### ISSUE THREAD

**Issue by tightly-clutched** [terraform-google-modules/terraform-google-network#254]
I'm trying to import an existing subnet from gcp into TF. The import command fails as follows

`james@mike ~ % terraform import module.vpc.module.subnets.google_compute_subnetwork["us-east1/dev-private-us-east1-7"] us-east1/dev-private-us-east1-7`
`zsh: no matches found: module.vpc.module.subnets.google_compute_subnetwork[us-east1/dev-private-us-east1-7]`

`terraform state list` shows existing subnets, but I can't decipher how to address that sub-module to import new ones.

`terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "3.46.0"
    }
  }
}`

**Comment by bharathkkb** [comment]
@tightly-clutched it maybe something like 
`terraform import module.vpc.module.subnets.google_compute_subnetwork.subnetwork["us-east1/dev-private-us-east1-7"]` The [resource name](https://github.com/terraform-google-modules/terraform-google-network/blob/adf9706e72dbac3c5380cb49676c799cf7ad1e35/modules/subnets/main.tf#L28) (google_compute_subnetwork.**subnetwork**) within the subnet module seems to be missing

**Comment by tightly-clutched** [comment]
When I type `terraform state list` I do see existing subnets with the same syntax, e.g.,
```
module.vpc.module.subnets.google_compute_subnetwork.subnetwork["us-east1/dev-private-us-east1-1"]
module.vpc.module.subnets.google_compute_subnetwork.subnetwork["us-east1/dev-private-us-east1-2"]
module.vpc.module.subnets.google_compute_subnetwork.subnetwork["us-east1/dev-public-us-east1"]```

**Comment by qwerty1979bg** [comment]
@tightly-clutched `zsh: no matches found` does not seem to come from Terraform, but from your Linux shell.

Maybe you need some escaping around the "[", perhaps try "\[" ?

If you still face an issue, you could also try temporarily running sh / bash, in case this is some zsh specific problem.

**Comment by tightly-clutched** [comment]
@qwerty1979bg Brilliant! Through some trial and error with single-quotes and double-quotes, it turns out that backslash worked!

`terraform import module.vpc.module.subnets.google_compute_subnetwork.subnetwork[\"us-east1/dev-private-us-east1-7\"] us-east1/dev-private-us-east1-7`

**Comment by tightly-clutched** [comment]
Issue was resolved because the shell was removing characters

**Comment by bharathkkb** [comment]
good catch, found some further examples here
https://www.terraform.io/docs/cli/commands/import.html#example-import-into-resource-configured-with-for_each
