### ISSUE TITLE
Unable to enable/disable Shared VPC resource

### ISSUE THREAD

**Issue by elauqsap** [terraform-google-modules/terraform-google-network#268]
I have a Service Account with both `roles/compute.xpnAdmin` and `roles/resourcemanager.projectIamAdmin` at folder level in an organization as defined [here](https://cloud.google.com/vpc/docs/provisioning-shared-vpc#create-shared). I am using this module and the submodule `fabric-net-svpc-access` to attach service projects to the host project. However, I am getting a permissions error:

```
Error: googleapi: Error 403: Required 'compute.organizations.enableXpnResource' permission for 'projects/host-project-id'
```

It seems to be because I am using this module at a folder level and not an org level which is a non-issue for the gcloud beta cli tool:
```
gcloud beta compute shared-vpc associated-projects add --host-project=host-project-id service-project-id
```

Am I doing something wrong on the TF side? This wasn't happening a few months ago and from what I can tell the only difference made on our end was migrating from `v0.12.6` to `v0.13.5`.

**Comment by bharathkkb** [comment]
Thanks for the report @elauqsap 
We will need a similar fix like https://github.com/terraform-google-modules/terraform-google-project-factory/pull/560
