### ISSUE TITLE
vpc-serverless-connector-beta availability on Terraform Registry

### ISSUE THREAD

**Issue by nikki-kapil-db** [terraform-google-modules/terraform-google-network#297]
When will vpc-serverless-connector-beta (https://github.com/terraform-google-modules/terraform-google-network/tree/master/modules/vpc-serverless-connector-beta) be available on the Terraform registry, under submodules here: https://registry.terraform.io/modules/terraform-google-modules/network/google/latest

**Comment by bharathkkb** [comment]
Hi @nikki-kapil-db 
Our general release cadence to the registry is ~ 2 weeks. You can also directly reference from the main branch if you need to use the submodule like ` source = "github.com/terraform-google-modules/terraform-google-network//modules/vpc-serverless-connector-beta"`
