### ISSUE TITLE
"subnet_private_access" parameter not captured 

### ISSUE THREAD

**Issue by amodsachintha** [terraform-google-modules/terraform-google-network#309]
When creating a subnet, the "subnet_private_access" parameter has no effect.

**module** version - 3.3.0
**terraform** version - 1.0.2 (Terraform Cloud)
**google** provider version - 3.75.0

![subnet_private_access](https://user-images.githubusercontent.com/20857200/126068205-9ba5d664-1376-48c7-834b-3a468f2bc94c.png)

**Comment by bharathkkb** [comment]
Hi @amodsachintha 

Could you paste a sample config for repro? 
I was unable to repro with the sample config below on `1.0.2`
```
provider "google" {
  version = "~> 3.75.0"
}

module "test-vpc-module" {
  source       = "terraform-google-modules/network/google"
  version      = "3.3.0"
  project_id   = var.project_id
  network_name = "test-network"

  subnets = [
    {
      subnet_name           = "subnet-01"
      subnet_ip             = "10.10.10.0/24"
      subnet_region         = "us-west1"
      subnet_private_access = "true"
    },
    {
      subnet_name           = "subnet-02"
      subnet_ip             = "10.10.20.0/24"
      subnet_region         = "us-west1"
      subnet_private_access = "true"
    },
  ]
}
```
