### ISSUE TITLE
module.subnets (from terraform-google-modules/network/google//modules/subnets) does not support Terraform version       │ 1.0.7.

### ISSUE THREAD

**Issue by richaslab** [terraform-google-modules/terraform-google-network#319]
Trying to use the Network module to create VPC and subnets. It throws the error:
Initializing modules...
╷
│ Error: Unsupported Terraform Core version
│
│   on .terraform\modules\subnets\modules\subnets\versions.tf line 18, in terraform:
│   18:   required_version = "~> 0.12.6"
│
│ Module module.subnets (from terraform-google-modules/network/google//modules/subnets) does not support Terraform version      
│ 1.0.7. To proceed, either choose another supported Terraform version or update this version constraint. Version constraints   
│ are normally set for good reason, so updating the constraint may lead to other errors or unexpected behavior.

Script:

main.tf
module "vpc" {
    source  = "terraform-google-modules/network/google"
    version = "~> 3.0"
    #source                                 = "./modules/vpc"
    network_name                           = var.network_name
    auto_create_subnetworks                = var.auto_create_subnetworks
    #routing_mode                           = var.routing_mode
    project_id                             = var.project_id
    #description                            = var.description
    shared_vpc_host                        = var.shared_vpc_host
    #delete_default_internet_gateway_routes = var.delete_default_internet_gateway_routes
    #mtu                                    = var.mtu
    subnets = [
        {
            subnet_name           = var.subnet_name
            subnet_ip             = var.subnet_ip
            subnet_region         = var.region
        }
    ]
}
Currently I am using Terraform v1.0.7
on windows_amd64

**Comment by morgante** [comment]
Are you using an old version of the module? Please try running `terraform init -upgrade`.

We allow any Terraform version above v0.12: https://github.com/terraform-google-modules/terraform-google-network/blob/master/modules/subnets/versions.tf#L18

**Comment by bharathkkb** [comment]
Feel free to reopen if still an issue
