### ISSUE TITLE
Unable to dynamically enable logging configuration for each firewall rules using module

### ISSUE THREAD

**Issue by ayushmankoul** [terraform-google-modules/terraform-google-network#320]
I am trying to replicate following code given in modules/firewalll-rules to enable logging configuration dynamically for each firewall rule but it throws an error.
`dynamic "log_config" {
    for_each = lookup(each.value, "log_config") == null ? [] : [each.value.log_config]
  content {
      metadata = log_config.value.metadata
    }
  }`

> Error: Unsupported block type

    on ..\module-firewallrules\main.tf line 17, in resource "google_compute_firewall" "rules":
    17:   dynamic "log_config" {
    Blocks of type "log_config" are not expected here.

**Comment by morgante** [comment]
Make sure you're using the latest Terraform provider for Google.
