### ISSUE TITLE
terraform-google-network/modules/fabric-net-svpc-access - google_compute_subnetwork_iam_binding

### ISSUE THREAD

**Issue by Tamsel123** [terraform-google-modules/terraform-google-network#325]
Mapping members to network user roles for shared vpc subnet is failing for more than one user/service account. 

Error: Invalid function argument
│
│   on modules/terraform-google-network/modules/fabric-net-svpc-access/main.tf line 32, in resource "google_compute_subnetwork_iam_binding" "network_users":
│   32:   members = compact(split(",", lookup(var.host_subnet_users,
│   33:     element(var.host_subnets, count.index))
│   34:   ))
│     ├────────────────
│     │ count.index is 0
│     │ var.host_subnet_users is map of tuple with 1 element
│     │ var.host_subnets is list of string with 1 element
│
│ Invalid value for "str" parameter: string required.

**Comment by Tamsel123** [comment]
tfvars definition for reference:

host_subnets        = ["xxxxxxxxxxxxxxxxxxxxx"] 
host_subnet_regions = ["us-east4"]
host_subnet_users = { xxxxxxxxxxxxxxxxxxxxx = [
  "serviceAccount:***********@cloudservices.gserviceaccount.com",
  "serviceAccount::***********@cloudservices.gserviceaccount.com"
  ]
}

**Comment by bharathkkb** [comment]
@terraform-google-modules/fabric-core could you PTAL
