### ISSUE TITLE
Support latest version of the Google provider

### ISSUE THREAD

**Issue by jackwhelpton** [terraform-google-modules/terraform-google-network#334]
This is a blocker for me at the moment... the network module relies on google < 4.0:

https://github.com/terraform-google-modules/terraform-google-network/blob/master/versions.tf

We have internal modules that now rely on >= 4.0 in order to remove deprecation warnings related to the way Workload Identity is configured, so Terraform is unable to solve for that.

I'll explore the changes in 4.0 further, if it turns out to be straightforward I can submit a PR if that's desirable.

**Comment by jackwhelpton** [comment]
Having reviewed the breaking changes, I don't see anything that relates to the resources this module creates. Here's a PR, any feedback welcome:

https://github.com/terraform-google-modules/terraform-google-network/pull/335

**Comment by bharathkkb** [comment]
fixed via https://github.com/terraform-google-modules/terraform-google-network/pull/335
