### ISSUE TITLE
Private Service Connect support

### ISSUE THREAD

**Issue by jawnsy** [terraform-google-modules/terraform-google-network#337]
### TL;DR

This module does not appear to support creating a Private Service Connect subnet, which means that it cannot be used with safer-cluster to create a private Kubernetes cluster. Ideally, I'd like to use this to manage my Shared VPC host project, including all subnetworks and firewall rules.

### Terraform Resources

```markdown
https://github.com/terraform-google-modules/cloud-foundation-fabric/blob/c34f4f2a2f7f5794bbe3f5b11a9f12cf1857370e/modules/net-vpc/main.tf#L260-L269
```

**Comment by bharathkkb** [comment]
Thanks for the report @jawnsy 
Does this module should satisfy your use case https://github.com/terraform-google-modules/terraform-google-sql-db/tree/master/modules/private_service_access

**Comment by bharathkkb** [comment]
@jawnsy does the above link help for this issue?
