### ISSUE TITLE
Module is missing needed tags

### ISSUE THREAD

**Issue by bishgupp** [terraform-google-modules/terraform-google-network#376]
### TL;DR

Module source repository has no tags.
The source repository for the module "network" for provider "google" has no tags and therefore failed to setup during a module registration process
<img width="971" alt="TFC_module_no_tags" src="https://user-images.githubusercontent.com/1261085/188716216-1fbcc803-f1ab-4538-9b10-f08baeaf1254.png">

### Expected behavior

that the module repo as the needed references 

### Terraform Configuration

```hcl
Add Module
This module will be created under the current organization, BishTech. Modules can be added from all supported VCS providers.
```

### Terraform Version

```sh
1.1.4
```

**Comment by bharathkkb** [comment]
@bishgupp I believe you may have a fork of this module in your private repo and need to publish [tags](https://github.com/terraform-google-modules/terraform-google-network/tags) to use it within a private registry. https://discuss.hashicorp.com/t/terraform-cloud-modules-tag-issue/9373 seems to have some info. Feel free to re open if needed.
