### ISSUE TITLE
Properties are not documented well

### ISSUE THREAD

**Issue by j-windsor** [terraform-google-modules/terraform-google-network#379]
Several properties on this module are not documented well. Here are some examples:

- `firewall_rules`: The description is simply “List of firewall rules”, the type is any, and the default is an empty array. I can roughly infer this is a list of something (from the default value), but that is all I know. At least provide me with the shape of the object so I can make good guesses.
- `subnets` and `routes`: No evidence other than the sample usage, but I’m pretty sure the type of `list(map(string))` is wrong. It seems to be some list of objects of some unknown shape.

Please improve documentation so users don't have to fish through the implementation to determine how to set properties.

**Comment by yuryninog** [comment]
Hi @j-windsor I have created a PR for managing this https://github.com/terraform-google-modules/terraform-google-network/pull/384
