### ISSUE TITLE
firewall_rules submodule google provider version range likely incorrect

### ISSUE THREAD

**Issue by j-windsor** [terraform-google-modules/terraform-google-network#380]
It says it requires `<5.0,>= 2.12` but when trying the example usage with 3.5.0 it fails with the error: `Blocks of type log_config are not expected here`.

I am assuming `log_config` was added to `google_compute_firewall` after 3.5.0 but this module claims compatibility all the way back to 2.12.0.

**Comment by apeabody** [comment]
Hi @j-windsor - Thanks for reaching out!  It looks like it was added in TPG 3.33.0, it should be fixed by #381
