### ISSUE TITLE
Cannot set source_ranges in firewall_rules

### ISSUE THREAD

**Issue by thangchinh** [terraform-google-modules/terraform-google-network#470]
### TL;DR

I cannot set `source_ranges` in `firewall_rules` param. Even I wrote custom value in `source_ranges`, I got `0.0.0.0/0` in `source_ranges`

### Expected behavior

`source_ranges` config in firewall must be the same as terraform configuration

### Observed behavior

`source_ranges` in `firewall_rules` becomes `0.0.0.0/0` 

### Terraform Configuration

```hcl
module "vpc" {
  source  = "terraform-google-modules/network/google"
  version = "~> 7.1"

  project_id   = var.project_id
  network_name = "${var.name}-vpc"
  routing_mode = "GLOBAL"

  firewall_rules = [
    {
      name      = "${var.name}-allow-ssh"
      direction = "INGRESS"
      allow = [{
        protocol = "tcp"
        ports    = ["22"]
      }]
      source_ranges = ["0.0.0.0/0"]
    },
    {
      name      = "${var.name}-allow-health-check"
      direction = "INGRESS"
      allow = [{
        ports    = ["80"]
        protocol = "tcp"
      }]
      source_ranges = ["130.211.0.0/22", "35.191.0.0/16"]
      target_tags   = ["allow-health-check"]
    },
    {
      name      = "${var.name}-allow-internal"
      direction = "INGRESS"
      allow = [
        {
          ports    = ["0-65535"]
          protocol = "tcp"
        },
        {
          ports    = ["0-65535"]
          protocol = "udp"
        },
        {
          protocol = "icmp"
        },
      ]
      source_ranges = ["10.0.0.0/8"]
    }
  ]

  subnets = [
    {
      subnet_name   = "subnet-01"
      subnet_ip     = "10.148.0.0/20"
      subnet_region = "asia-southeast1"
    },
    {
      subnet_name   = "subnet-02"
      subnet_ip     = "10.128.0.0/20"
      subnet_region = "us-central1"
    },
  ]

}
```

### Terraform Version

```sh
Terraform v1.5.1
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.72.1
+ provider registry.terraform.io/hashicorp/google-beta v4.72.1
+ provider registry.terraform.io/hashicorp/random v3.5.1

Your version of Terraform is out of date! The latest version
is 1.5.2. You can update by downloading from https://www.terraform.io/downloads.html
```

**Comment by imrannayer** [comment]
@thangchinh Can you pass it as follows:

```
ranges = ["130.211.0.0/22", "35.191.0.0/16"]
```

Module converts the value into `source_ranges` or `destination_ranges` depending on the direction (INGRESS/EGRESS)

**Comment by dindurthy** [comment]
Yeah, but what if you want to set both, e.g. permit source_range egress to destination_range?

**Comment by cblkwell** [comment]
Actually, you can. If you explicitly set `source_ranges` or `destination_ranges`, you can add these. The automatic setting is only done if you *just* specify `ranges` alone (I didn't realize this until a close read of the code myself).

**Comment by imrannayer** [comment]
@dindurthy root module is calling `firewall-rules` sub-module. You can find inputs [here](https://github.com/terraform-google-modules/terraform-google-network/blob/master/modules/firewall-rules/README.md). There are two parameters `ingress_rules` and `egress_rules` which can be used for passing both simultaneously. `rules` variable is obsolete.
