### ISSUE TITLE
subnets_secondary_ranges

### ISSUE THREAD

**Issue by MichelBoucey** [terraform-google-modules/terraform-google-network#50]
I don't know if I am doing the right thing... I try and I cannot get values from output `subnets_secondary_ranges`:

subnets = [
        {
            subnet_name           = "${var.project_id}-subnet-0"
            subnet_ip             = "10.0.0.0/20"
            subnet_region         = "${var.region}"
        },
    ]
    secondary_ranges = {
        "${var.project_id}-subnet-0" = [
            {
                range_name    = "${var.project_id}-subnet-0-services"
                ip_cidr_range = "172.16.0.0/20"
            },
            {
                range_name    = "${var.project_id}-subnet-0-pods"
                ip_cidr_range = "172.16.16.0/20"
            },
        ]
    }

to fullfill `terraform-google-kubernetes-engine` inputs `ip_range_services` and `ip_range_pods`: 

  ip_range_services       = "${module.vpc.subnets_secondary_ranges}"
  ip_range_pods           = "${module.vpc.subnets_secondary_ranges[0]}"

Error: Error refreshing state: 2 errors occurred:
	* module.gke.var.ip_range_pods: variable ip_range_pods in module gke should be type string, got list
	* module.gke.var.ip_range_services: variable ip_range_services in module gke should be type string, got list

**Comment by aaron-lane** [comment]
Hi @MichelBoucey, thank you for your interest in the project!

`subnets_secondary_ranges` is actually a list of lists as it is [aggregated from multiple data sources](https://github.com/terraform-google-modules/terraform-google-network/blob/master/outputs.tf#L63). You will need to traverse further in to the object to find the values.

**Comment by MichelBoucey** [comment]
Hi @aaron-lane,

Sorry for late reply... that's OK now, with a so simple solution:

ip_range_services = "${var.project_id}-subnet-0-services"

Thanks for help.
