### ISSUE TITLE
using net-shared-vpc-access with tf 0.12.6 errors out with "Invalid value for "inputMap" parameter: lookup() requires a map as the first argument."

### ISSUE THREAD

**Issue by vital4ik** [terraform-google-modules/terraform-google-network#59]
using this module with the following config
```hcl
module "net-shared-vpc-access" {
  source = "terraform-google-modules/network/google//modules/fabric-net-svpc-access"

  host_project_id = "${data.terraform_remote_state.vpchost.outputs.project_id}"

  service_project_num = 1

  service_project_ids = ["${data.terraform_remote_state.vpcservice1.outputs.project_id}"]

  host_subnets = ["${data.terraform_remote_state.vpchost.outputs.east_subnetwork_id}", "${data.terraform_remote_state.vpchost.outputs.west_subnetwork_id}"]

  host_subnet_regions = ["us-east1", "us-west1"]

  host_subnet_users = ["serviceAccount:${data.terraform_remote_state.vpcservice1.outputs.default_account}", "serviceAccount:${data.terraform_remote_state.vpcservice1.outputs.default_account}"]
}
```
produces the error:

> Error: Invalid function argument

  on .terraform/modules/net-shared-vpc-access/terraform-google-modules-terraform-google-network-2ada6f9/modules/fabric-net-svpc-access/main.tf line 30, in resource "google_compute_subnetwork_iam_binding" "subnets":
  30:   members = compact(split(",", lookup(var.host_subnet_users,
  31:
    |----------------
    | var.host_subnet_users is tuple with 2 elements

Invalid value for "inputMap" parameter: lookup() requires a map as the first
argument.

**Comment by vital4ik** [comment]
digging deeper, looks like the example is not correct and after switching to map the code looks like this:
`module "net-shared-vpc-access" {
  source              = "terraform-google-modules/network/google//modules/fabric-net-svpc-access"
  host_project_id     = "${data.terraform_remote_state.vpchost.outputs.project_id}"
  host_subnets        = ["${data.terraform_remote_state.vpchost.outputs.east_subnetwork_name}","${data.terraform_remote_state.vpchost.outputs.west_subnetwork_name}"]
  host_subnet_regions = ["us-east1","us-west1"]
  host_subnet_users   = {serviceAccount:"${data.terraform_remote_state.vpcservice1.outputs.default_account}",serviceAccount:"${data.terraform_remote_state.vpcservice1.outputs.default_account}"}
  service_project_num = 1
  service_project_ids = ["${data.terraform_remote_state.vpcservice1.outputs.project_id}"]
}`
and error has changed as well:

> Error: Invalid function argument

  on .terraform/modules/net-shared-vpc-access/terraform-google-modules-terraform-google-network-2ada6f9/modules/fabric-net-svpc-access/main.tf line 30, in resource "google_compute_subnetwork_iam_binding" "subnets":
  30:   members = compact(split(",", lookup(var.host_subnet_users,
  31:
    |----------------
    | var.host_subnet_users is object with 1 attribute "serviceAccount"

Invalid value for "inputMap" parameter: the given object has no attribute
"east-subnet".

where east-subnet is the name of the first subnet in the list

**Comment by morgante** [comment]
Thanks for the report.

@ludoo Can you take a look at this?

**Comment by vital4ik** [comment]
hi, if there are any workaround for this issue while you are investigating I need to implement it:)

**Comment by ludoo** [comment]
Sorry for lagging, summer time is always hard... :)

Yes the example is incorrect, `host_subnet_users` needs to be a map, with subnet names as keys and comma-delimited users as values. Will get back to you ASAP with a working example.

**Comment by ludoo** [comment]
I just tested the example, and it works fine: apply finishes with no issues. My earlier statement holds: `host_subnet_users` has to be a map with keys matching subnet names, and the example does that (so it's not incorrect as I wrote above):

```
 host_subnet_users = {
    first  = "${local.first_gce_sa},${local.second_gce_sa}"
    second = local.second_gce_sa
  }
```

I am closing this, feel free to reopen if you still think there's an issues, but please provide evidence you're passing in an actual map in `host_subnet_users`.
