### ISSUE TITLE
next_hop_internet should be able to handle a boolean

### ISSUE THREAD

**Issue by emailbob** [terraform-google-modules/terraform-google-network#63]
The variable `next_hop_internet` should be able to handle a boolean value similar to the variables:
shared_vpc_host
subnet_private_access
subnet_flow_logs

The below config throws an error because `next_hop_internet` requires "true"
```    
routes = [
  {
    name = "egress-internet"
    description = "route through IGW to access internet"
    destination_range = "0.0.0.0/0"
    tags = "egress-inet"
    next_hop_internet = true
  }
]
```

**Comment by aaron-lane** [comment]
@emailbob can you verify if #64 fixes your issue?

**Comment by emailbob** [comment]
Sorry for the delay

Yes the bool `next_hop_internet = true` does work. But when I also tested with `next_hop_internet = false`

I get the error:
```
Error: Error creating Route: googleapi: Error 400: Invalid resource usage: 'A Route must specify at least one type of next hop.'., invalidResourceUsage
```
