### ISSUE TITLE
Beta provider support

### ISSUE THREAD

**Issue by Dev25** [terraform-google-modules/terraform-google-network#68]
Do we intend to have this module expose beta options as a separate module similar to how the GKE module provides this by using templating?

In my use case next hop ILB for routes is currently in the [beta provider](https://www.terraform.io/docs/providers/google/r/compute_route.html#next_hop_ilb) and i would like to see it exposed in this module.

That being said there is a workaround (declare beta route resource outside this module), so it's not a blocker but more of a nice to have.

**Comment by morgante** [comment]
I think we could introduce a separate beta submodule.

**Comment by aaron-lane** [comment]
Target the 2.0 release branch.

**Comment by nick4fake** [comment]
We should probably also cover https://www.terraform.io/docs/providers/google/r/compute_subnetwork.html
purpose and role

**Comment by nick4fake** [comment]
Ticket for real-life usage:
https://github.com/terraform-google-modules/terraform-google-network/issues/132
