### ISSUE TITLE
Updating any subnet in a list causes subsequent subnets to be re-created

### ISSUE THREAD

**Issue by onetwopunch** [terraform-google-modules/terraform-google-network#70]
## Expected behavior

When a subnet is modfied in source, only one resource is modified in the `plan`/`apply`

##  Actual behavior

When a subnet in the list of `var.subnets` is updated or deleted, it forces recreation of all subsequent subnets in the list.

## Example

If I were to update the `subnet_ip` for `subnet-01` it would force re-creation of `subnet-02` as well.

```
module "vpc" {
    source  = "terraform-google-modules/network/google"
    version = "~> 1.0.0"
  
   ...  
   
    subnets = [
        {
            subnet_name           = "subnet-01"
            subnet_ip             = "10.10.10.0/24"
            subnet_region         = "us-west1"
        },
        {
            subnet_name           = "subnet-02"
            subnet_ip             = "10.10.20.0/24"
            subnet_region         = "us-west1"
            subnet_private_access = "true"
            subnet_flow_logs      = "true"
            description           = "This subnet has a description"
        },
    ]
    ...
}
```

**Comment by tfhartmann** [comment]
I also ran into this and started a feature branch that I got working. I should be able to open a PR later today 😄
