### ISSUE TITLE
Error: Error in function call - google_compute_subnetwork.subnetwork is empty tuple

### ISSUE THREAD

**Issue by agno01** [terraform-google-modules/terraform-google-network#80]
main.tf content:

```
module "vpc" {
  source  = "terraform-google-modules/network/google"
  version = "v1.2.0"

  project_id   = var.projectid
  network_name = var.clusterid_network
  routing_mode = "GLOBAL"

  subnets = [
    {
      subnet_name   = var.clusterid_subnet
      subnet_ip     = var.clusterid_subnet_cidr
      subnet_region = var.region
    }
  ]
}
```

After running `terraform plan/apply`, following error shows up:

```
Error: Error in function call

  on .terraform/modules/vpc/terraform-google-modules-terraform-google-network-7b0ee13/main.tf line 56, in data "google_compute_subnetwork" "created_subnets":
  56:   name    = element(google_compute_subnetwork.subnetwork.*.name, count.index)
    |----------------
    | count.index is 0
    | google_compute_subnetwork.subnetwork is empty tuple

Call to function "element" failed: cannot use element function with an empty
list.
```

**Comment by agno01** [comment]
Interesting that when I deleted the state file (leftover after `terraform destroy`) it went fine even without adding the `depends_on` condition.

**Comment by morgante** [comment]
Interesting. I'm not quite sure what's going on here, but your proposed fix is harmless so happy to add it.

**Comment by Jeanno** [comment]
Does this error still persist after the #93 rollback? 
What I suspect is that the problem shows if you apply once, destroy once, and wants to plan the tf scripts again. At this point, when Terraform wants to check up the data (subnetwork in this case, which is empty), there's a discrepancy between length(var.subnets) and the data, which causes the error.

**Comment by Jeanno** [comment]
I've seen similar pattern of error in the GCS module as well. The pattern is like this:

1) `terraform apply`
2) `terraform destroy`  or  Change the length of an array variable
3) `terraform apply` or `terraform plan`
4) Error. Step 3 is not processed.

Does it make sense to extend test cases in all module to cover the above error pattern as well?

**Comment by morgante** [comment]
Yes, I think we should add some smoke testing around deletion, at least on targeted modules where we've seen issues.
