### ISSUE TITLE
Make `subnet_flow_logs` and `subnet_private_access` into string variables

### ISSUE THREAD

**Issue by ocervell** [terraform-google-modules/terraform-google-network#9]

**Comment by morgante** [comment]
Terraform recommends against having boolean input variables, instead using strings for consistency: https://www.terraform.io/docs/configuration/variables.html#booleans

**Comment by andreyk-code** [comment]
Even though "subnet_flow_logs and "subnet_private_access" technically aren't input variables (the subnets list is the input variable), should we convert them into strings for consistency with "shared_vpc_host" being a string?

**Comment by morgante** [comment]
Yes, I think we should. Renaming this accordingly.

**Comment by andreyk-code** [comment]
#13

**Comment by andreyk-code** [comment]
PR submitted with fix: #13

**Comment by andreyk-code** [comment]
Closing as fixed with merge of PR.
