### ISSUE TITLE
Output variable subnets_secondary_ranges cannot be used in dependent modules.

### ISSUE THREAD

**Issue by rbrondgeest** [terraform-google-modules/terraform-google-network#92]
A new bug is introduced into this module, due to the introduction of the following code:
https://github.com/terraform-google-modules/terraform-google-network/pull/81

As written in https://www.terraform.io/docs/configuration/data-sources.html#data-resource-dependencies adding a `depends_on` in a `data` declaration, the execution of the data value is postponed to the apply phase of terraform. 
The `created_subnets` value is being used in the output of the module for outputting the `subnets_secondary_ranges`. 
We are using the secondary ranges in other modules, as they depend on these ranges (a kubernetes cluster uses secondary ranges for its pods and containers).
Running a terraform plan & apply will now always cause a replacement of the kubernetes cluster, as terraform is not able to find the diff of the state during the `plan` phase.

To fix this issue we need to get rid of the depends_on in the data block. Perhaps this PR already fixes the issue, but just for 2.x:
https://github.com/terraform-google-modules/terraform-google-network/pull/73

Could a patch be created for a 1.4.1 or whatsoever bugfix release?

**Comment by morgante** [comment]
Thanks for the report, v1.4.1 should fix this.

**Comment by jantoebes** [comment]
And thank you @morgante for providing a solution so fast :-)
