### ISSUE TITLE
Using fabric-net-svpc-access module breaks GKE

### ISSUE THREAD

**Issue by ideasculptor** [terraform-google-modules/terraform-google-network#97]
If you use the fabric-net-svpc-access module to associate a project to a host vpc project, and you set host_service_agent_role to true, the kubernetes service agent in the service project is NOT granted the roles/container.hostServiceAgentUser role.

I'm assuming that it gets created correctly, by default, when simply setting shared_vpc_enabled and shared_vpc in the project_factory module, since I have a project created that way, and the service-<projectnum>@container-engine-robot.iam.gserviceaccount.com for that project does have that role on the host project.  

In the project where I specify no shared_vpc_enabled, but then explicitly use the fabric-net-svpc-access module to associated the host project with the service project, only the explicitly listed host_service_agent_users are granted that role.  

It looks to me like the default kubernetes service agent account (service-[PROJECT_NUMBER]@container-engine-robot.iam.gserviceaccount.com) should automatically be added to that list, or the docs should at least specify how to construct that account identifier manually in order to ensure it is included.

The error message resulting from the missing role points users to this page, which really isn't entirely accurate - https://cloud.google.com/kubernetes-engine/docs/troubleshooting#gke_service_account_deleted

In this case, the problem is not resolved by disabling and re-enabling the kubernetes api, nor was it caused by deleting the service account.  

And while I have you, if service accounts are going to have the project NUMBER in them, can we please also have the project number visible in the resource manager in the console?  It is obnoxious to have to click through to the settings on each project, which loads a completely new page, just to see each project's number.  Simply figuring out which projects' service accounts had the role and why took far too long, because I had no easy way to correlate the list of accounts with the list of projects visible in resource manager.  I had to check each one.  Project number keeps cropping up in various contexts, and it continues to be a PITA whenever it does because it isn't readily visible in the UI.  Why not use project_id instead of project num, or else make project num just as visible as the project id is?

**Comment by ideasculptor** [comment]
```Error: Error waiting for creating GKE cluster: Google Compute Engine: Required 'compute.subnetworks.get' permission for 'projects/refarch-dev-e5ee/regions/us-central1/subnetworks/dev-us-central1-gke'.
```

It looks like the service agent account needs to be Compute Network User, too, though I am still debugging that error, since it takes 10 minutes for each iteration to error out and the error message doesn't bother to tell me which entity is lacking the permission.

I added compute network user for the specific subnet to the group that is executing the module, and that didn't fix it.  Now I have added that role to the kubernetes service agent account and I'm waiting to see what happens.

Either way, using the fabric-net-svpc-access module doesn't work for kubernetes unless you do a lot of manual massaging.

**Comment by ludoo** [comment]
What we probably did not make explicit in this submodule's docs is that a) it's designed for the `fabric` end to end samples and not meant to implicitly mesh with the `project-factory` main module, and b) that usage examples are in the `cloud-foundation-fabric` repository. This is the canonical example of how to use it for GKE

https://github.com/terraform-google-modules/cloud-foundation-fabric/blob/master/infrastructure/shared-vpc/main.tf#L121

I'm pretty sure the submodule works for GKE, but I cannot verify your report at the moment as I'm hit by [this issue](https://status.cloud.google.com/incident/compute/19008). Let's keep this open for a while until you test the configuration in the link above, or I manage to get past the issue above and run our SVPC example, which I have not done in a while.
That said, I'm having issues creating GKE clusters or even enabling the Compute API

**Comment by ludoo** [comment]
Managed to re-test our Shared VPC setup and create a cluster using the subnetwork shared with the GKE project. I'm going to close this, please refer to the code linked above for details on how to set up subnetwork access for GKE.
